accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", view=views.register_view, name="register"),
    path("login/", view=views.login_view, name="login"),
    path("logout/", view=views.logout_view, name="logout"),

    path("password/change/", view=views.change_password_view, name="change_password"),

    path("favorites/", view=views.favorites_view, name="favorites"),
    path("favorites/add/<int:article_pk>", view=views.add_to_favorites_view, name="add_to_favorites"),
    path("favorites/remove/<int:article_pk>", view=views.remove_from_favorites_view, name="remove_from_favorites"),
]

api/urls.py
from django.urls import path

from . import views

app_name = "api"

urlpatterns = [
    path("articles/", view=views.ArticleAPIView.as_view()),
    path("articles/<int:pk>", view=views.RetrieveArticleAPIView.as_view()),
    path("auth/register/", view=views.RegisterAPIView.as_view()),
    path("auth/confirm/<str:code>", view=views.ConfirmUser.as_view())
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="NEWS API",
      default_version='v1',
      description="NEWS API DESCRIPTION",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="dasifue@gmail.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('', include("news.urls")),
    path('accounts/', include("accounts.urls")),
    path('api/auth/', include('djoser.urls.authtoken')),
    path('api/auth/', include('djoser.urls.jwt')),
    path('api/swagger/', schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path

from . import views

app_name = "news"

urlpatterns = [
    path('', views.index, name='index'), #home page
    path('article/<int:pk>', views.article_details_view, name="details"),
    path('article/create/', views.article_creation_view, name="article_creation"),
    path('article/update/<int:pk>', views.article_update_view, name="article_update"),
    path('article/delete/<int:pk>', views.delete_article_view, name="delete_article"),

    path('comment/create/<int:article_pk>', views.create_comment_view, name="comment_create"),
    path('comment/create/<int:article_pk>/parent/<int:parent_pk>', views.create_comment_view, name="comment_answer"),
    path('comment/update/<int:pk>', views.comment_update_view, name="comment_update"),
    path('comment/delete/<int:pk>', views.delete_comment_view, name="comment_delete"),

    path('search/', views.search_view, name="search")
]

accounts/models.py
from collections.abc import Iterable
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    avatar = models.ImageField(verbose_name="Аватар", upload_to="avatars/", default="default/avatar.jpg", blank=True)
    email = models.EmailField(verbose_name="Почта", unique=True)
    biography = models.TextField(verbose_name="Биография", null=True, blank=True)
    job = models.CharField(verbose_name="Профессия", max_length=50, null=True, blank=True)
    favorites = models.ManyToManyField("news.Article", related_name="users", verbose_name="Фавориты", blank=True)
    is_active = models.BooleanField(verbose_name="Подтверждён", default=False)

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return f"{self.username} - {self.email}"
    
    @property
    def full_name(self):
        full_name = f"{self.first_name} {self.last_name}"
        return full_name.strip()

accounts/forms.py
from typing import Any
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password

from .models import User


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(max_length=50, widget=forms.PasswordInput())
    password_confirm = forms.CharField(max_length=50, widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "email", "password", "password_confirm")
    
    
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data["password"]
        password_confirm = cleaned_data["password_confirm"]

        if password != password_confirm:
            raise ValidationError(message={"password":"Пароли не совпали!"}) 

        return super().clean()
        

class ChangePasswordForm(forms.Form):
    real_password = forms.CharField(max_length=50)
    new_password = forms.CharField(max_length=50, validators=[validate_password])
    new_password_confirm = forms.CharField(max_length=50, validators=[validate_password])

    def clean(self):
        password = self.cleaned_data["new_password"]
        password_confirm = self.cleaned_data["new_password_confirm"]

        if password != password_confirm:
            raise ValidationError(message={"new_password":"Пароли не совпали!"}) 

        return super().clean()

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .models import User
from .forms import UserRegistrationForm, ChangePasswordForm

from news.models import Article


def register_view(request): 
    form = UserRegistrationForm() # Определяется пустая форма для регистрации пользователя
 
    if request.method == "POST": # Если пользователь ввёл данные в html форму и отправил их на сервер
        print(request.POST)
        form = UserRegistrationForm(data=request.POST) # передаём данные в форму
        if form.is_valid(): # форма проверяет данные
            user = User.objects.create( # создаём пользователя
                username = form.cleaned_data['username'], # передаём пользователю username
                email = form.cleaned_data['email'], # передаём пользователю email
            )
            user.set_password(raw_password=form.cleaned_data['password']) # хешируем пароль пользователя
            user.save() # сохранение пользователя
            return redirect("accounts:login") # перенаправление пользователя на страницу авторизации
    

    context = { # определение контекса
        "form": form
    }
    # отправка контекстных данных на html шаблон
    return render(request=request, template_name="register.html", context=context)


def login_view(request):
    if request.method == "POST": # получаем POST запрос с его данными
        username = request.POST.get("username") # достаём из запроса username
        password = request.POST.get("password") # достаём из запроса password
        user = authenticate(request, username=username, password=password) # проверяем username и password на существование
        if user is not None: # Если пользователь с таким username и password найден
            login(request, user) # авторизуем пользователя
            return redirect("news:index") # перенаправляем его на главную страницу
        
        context = {
            "error": "Ошибка! Проверьте username и password!"
        }
        return render(request=request, template_name="login.html", context=context)
    return render(request=request, template_name="login.html")


def logout_view(request):
    logout(request=request) # Вынести пользователя из системы (выйти из аккаунта)
    return redirect("accounts:login")


@login_required # декоратор, перенаправляющий пользователя на страицу авторизации, если он не авторизован
def change_password_view(request):
    # if not request.user.is_authenticated: # если пользователь не авторизован
    #     return redirect("accounts:login") # перенапрваление к авторизации

    form = ChangePasswordForm() # Определяем пустую форму
    user: User = request.user # находим авторизованного пользователя

    context = { # определяем контекстные данные, которые будут отправлены на фронт
        "form": form
    }

    if request.method == "POST": # Если пользоваатель отправил POST запрос с данными для изменения пароля
        form = ChangePasswordForm(data=request.POST) # отправляем полученные данные из фронта в форму
        real_password = request.POST['real_password'] # достаём вручную действительный пароль пользователя из POST запроса

        if not user.check_password(real_password): # check_password - проверка на действительность введённого пароля
            context.update({"error": "Неправильный пароль!"}) # добавление ошибки, если пароль не действительный

        elif form.is_valid():  # is_valid - проверка новых паролей
            user.set_password(raw_password=form.cleaned_data['new_password']) # Меняем пароль у пользователя и хешируем его
            user.save() # сохранение изменений в бд
            logout(request) # выход из системы
            return redirect("accounts:login") # перенаправление на страницу авторизации
    
    context.update({"form": form}) # обновление контекста
    return render(request=request, template_name="change_password.html", context=context) # отправка context данных на html страницу


@login_required
def add_to_favorites_view(request, article_pk: int):
    article = get_object_or_404(Article, id=article_pk)
    user: User = request.user
    user.favorites.add(article)
    return redirect(request.META.get("HTTP_REFERER", "/"))


@login_required
def remove_from_favorites_view(request, article_pk: int):
    article = get_object_or_404(Article, id=article_pk)
    user: User = request.user
    user.favorites.remove(article)
    return redirect(request.META.get("HTTP_REFERER", "/"))


@login_required
def favorites_view(request):
    user: User = request.user
    articles = user.favorites.all()

    context = {
        "articles": articles 
    }
    return render(request=request, template_name="favorites.html", context=context)

accounts/templates/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block content %} 

<!-- <div class="heading-page header-text">
    <div class="row">
        <div class="col-lg-8">

            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Register">
            </form>

        </div>
    </div>
</div> -->


<section class="contact-us">
    <div class="container">
      <div class="row">
      
        <div class="col-lg-12">
          <div class="down-contact">
            <div class="row">
              <div class="col-lg-8">
                <div class="sidebar-item contact-form">
                  <div class="sidebar-heading">
                    <h2>Send us a message</h2>
                  </div>
                  <div class="content">
                    <form id="contact" action="" method="post">
                        {% csrf_token %}
                      <div class="row">
                        <div class="col-md-12 col-sm-12">
                          <fieldset>
                                {{ error }}
                            <input name="real_password" type="password" id="name" placeholder="Current password" required>
                          </fieldset>
                        </div>
                        <div class="col-md-12 col-sm-12">
                            <fieldset>
                                {{ form.new_password.errors }}
                              <input name="new_password" type="password" id="name" placeholder="New password" required>
                            </fieldset>
                          </div>
                        <div class="col-md-12 col-sm-12">
                          <fieldset>
                                {{ form.new_password_confirm.errors }}
                            <input name="new_password_confirm" type="password" id="subject" placeholder="Confirm new password" required>
                          </fieldset>
                        </div>
                        <div class="col-lg-12">
                          <fieldset>
                            <button type="submit" id="form-submit" class="main-button">Change password</button>
                          </fieldset>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="sidebar-item contact-information">
                  <div class="sidebar-heading">
                    <h2>contact information</h2>
                  </div>
                  <div class="content">
                    <ul>
                      <li>
                        <h5>090-484-8080</h5>
                        <span>PHONE NUMBER</span>
                      </li>
                      <li>
                        <h5>info@company.com</h5>
                        <span>EMAIL ADDRESS</span>
                      </li>
                      <li>
                        <h5>123 Aenean id posuere dui, 
                            <br>Praesent laoreet 10660</h5>
                        <span>STREET ADDRESS</span>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

{% endblock %}


    

accounts/templates/favorites.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="blog-posts">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">

                {% for article in articles %}

                <div class="col-lg-12">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      {% if article.image %}
                      <img src="{{ article.image.url }}" alt="">
                      {% endif %}
                    </div>
                    <div class="down-content">
                      <span>{{ article.category.name }}</span>
                      <a href="{% url 'news:details' pk=article.pk %}"><h4>{{ article.name }}</h4></a>
                      <ul class="post-info">
                        <li><a href="#">{{ article.owner.username }}</a></li>
                        <li><a href="#">{{ article.updated }}</a></li>
                        <li><a href="#">12 Comments</a></li>
                      </ul>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-6">
                            <ul class="post-tags">
                              {% if request.user not in article.users.all %}
                              <a href="{% url 'accounts:add_to_favorites' article_pk=article.id %}">
                                <li><i class="fa fa-heart-o"></i></li>
                                <li>{{ article.users.count }}</li>
                              </a>
                              {% else %}
                              <a href="{% url 'accounts:remove_from_favorites' article_pk=article.id %}">
                                <li><i class="fa fa-heart"></i></li>
                                <li>{{ article.users.count }}</li>
                              </a>
                              {% endif %}
                            </ul>
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              {% for tag in article.tags.all %}
                              <li><a href="#">{{ tag.name }}</a></li>
                              {% endfor %}
                            </ul>
                          </div>
                          <div class="col-6">
                            <ul class="post-share">
                              <li><i class="fa fa-share-alt"></i></li>
                              <li><a href="#">Facebook</a>,</li>
                              <li><a href="#"> Twitter</a></li><br>
                              {% if article.owner == request.user %}
                              <a href="{% url 'news:delete_article' pk=article.id %}"><li><i class="fa fa-trash"></i></li></a>
                              {% endif %}
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                {% empty %}
                <h1>Нет фаворитов</h1>
                {% endfor %}

                <div class="col-lg-12">
                  <div class="main-button">
                    <a href="blog.html">View All Posts</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="sidebar">
              <div class="row">
                <div class="col-lg-12">
                  <div class="sidebar-item search">
                    <form id="search_form" name="gs" method="GET" action="#">
                      <input type="text" name="q" class="searchText" placeholder="type to search..." autocomplete="on">
                    </form>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item recent-posts">
                    <div class="sidebar-heading">
                      <h2>Recent Posts</h2>
                    </div>
                    <div class="content">
                      <ul>
                        <li><a href="post-details.html">
                          <h5>Vestibulum id turpis porttitor sapien facilisis scelerisque</h5>
                          <span>May 31, 2020</span>
                        </a></li>
                        <li><a href="post-details.html">
                          <h5>Suspendisse et metus nec libero ultrices varius eget in risus</h5>
                          <span>May 28, 2020</span>
                        </a></li>
                        <li><a href="post-details.html">
                          <h5>Swag hella echo park leggings, shaman cornhole ethical coloring</h5>
                          <span>May 14, 2020</span>
                        </a></li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item categories">
                    <div class="sidebar-heading">
                      <h2>Categories</h2>
                    </div>
                    <div class="content">
                      <ul>
                        <li><a href="#">- Nature Lifestyle</a></li>
                        <li><a href="#">- Awesome Layouts</a></li>
                        <li><a href="#">- Creative Ideas</a></li>
                        <li><a href="#">- Responsive Templates</a></li>
                        <li><a href="#">- HTML5 / CSS3 Templates</a></li>
                        <li><a href="#">- Creative &amp; Unique</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item tags">
                    <div class="sidebar-heading">
                      <h2>Tag Clouds</h2>
                    </div>
                    <div class="content">
                      <ul>
                        <li><a href="#">Lifestyle</a></li>
                        <li><a href="#">Creative</a></li>
                        <li><a href="#">HTML5</a></li>
                        <li><a href="#">Inspiration</a></li>
                        <li><a href="#">Motivation</a></li>
                        <li><a href="#">PSD</a></li>
                        <li><a href="#">Responsive</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %} 

<!-- <div class="heading-page header-text">
    <div class="row">
        <div class="col-lg-8">

            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Register">
            </form>

        </div>
    </div>
</div> -->


<section class="contact-us">
    <div class="container">
      <div class="row">
      
        <div class="col-lg-12">
          <div class="down-contact">
            <div class="row">
              <div class="col-lg-8">
                <div class="sidebar-item contact-form">
                  <div class="sidebar-heading">
                    <h2>Send us a message</h2>
                  </div>
                  <div class="content">
                    <form id="contact" action="" method="post">
                        {% csrf_token %}
                      <div class="row">
                        <div class="col-md-12 col-sm-12">
                          <fieldset>
                            <input name="username" type="text" id="name" placeholder="Your username" required>
                          </fieldset>
                        </div>
                        <div class="col-md-12 col-sm-12">
                          <fieldset>
                            <input name="password" type="password" id="subject" placeholder="Your password" required>
                          </fieldset>
                        </div>
                        {{ error }}
                        <div class="col-lg-12">
                          <fieldset>
                            <button type="submit" id="form-submit" class="main-button">Login</button>
                          </fieldset>
                          <p>Нет аккаунта - <a href="{% url 'accounts:register' %}">Sign Up</a></p>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="sidebar-item contact-information">
                  <div class="sidebar-heading">
                    <h2>contact information</h2>
                  </div>
                  <div class="content">
                    <ul>
                      <li>
                        <h5>090-484-8080</h5>
                        <span>PHONE NUMBER</span>
                      </li>
                      <li>
                        <h5>info@company.com</h5>
                        <span>EMAIL ADDRESS</span>
                      </li>
                      <li>
                        <h5>123 Aenean id posuere dui, 
                            <br>Praesent laoreet 10660</h5>
                        <span>STREET ADDRESS</span>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

{% endblock %}


    

accounts/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %} 

<!-- <div class="heading-page header-text">
    <div class="row">
        <div class="col-lg-8">

            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Register">
            </form>

        </div>
    </div>
</div> -->


<section class="contact-us">
    <div class="container">
      <div class="row">
      
        <div class="col-lg-12">
          <div class="down-contact">
            <div class="row">
              <div class="col-lg-8">
                <div class="sidebar-item contact-form">
                  <div class="sidebar-heading">
                    <h2>Send us a message</h2>
                  </div>
                  <div class="content">
                    <form id="contact" action="{% url 'accounts:register' %}" method="post">
                        {% csrf_token %}
                      <div class="row">
                        <div class="col-md-6 col-sm-12">
                          <fieldset>
                            {{ form.username.errors }}
                            <input name="username" type="text" id="name" placeholder="Your username" required>
                          </fieldset>
                        </div>
                        <div class="col-md-6 col-sm-12">
                          <fieldset>
                            {{ form.email.errors }}
                            <input name="email" type="text" id="email" placeholder="Your email" required>
                          </fieldset>
                        </div>
                        <div class="col-md-6 col-sm-12">
                          <fieldset>
                            {{ form.password.errors }}
                            <input name="password" type="password" id="subject" placeholder="Your password" required>
                          </fieldset>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <fieldset>
                            {{ form.password_confirm.errors }}
                              <input name="password_confirm" type="password" id="subject" placeholder="Confirm password" required>
                            </fieldset>
                          </div>
                        
                        <div class="col-lg-12">
                          <fieldset>
                            <button type="submit" id="form-submit" class="main-button">Register</button>
                          </fieldset>
                          <p>Уже есть аккаунт - <a href="{% url 'accounts:login' %}">Sign In</a></p>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="sidebar-item contact-information">
                  <div class="sidebar-heading">
                    <h2>contact information</h2>
                  </div>
                  <div class="content">
                    <ul>
                      <li>
                        <h5>090-484-8080</h5>
                        <span>PHONE NUMBER</span>
                      </li>
                      <li>
                        <h5>info@company.com</h5>
                        <span>EMAIL ADDRESS</span>
                      </li>
                      <li>
                        <h5>123 Aenean id posuere dui, 
                            <br>Praesent laoreet 10660</h5>
                        <span>STREET ADDRESS</span>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

{% endblock %}


    