accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", view=views.register_view, name="register"),
    path("login/", view=views.login_view, name="login"),
    path("logout/", view=views.logout_view, name="logout"),

    path("password/change/", view=views.change_password_view, name="change_password"),

    path("favorites/", view=views.favorites_view, name="favorites"),
    path("favorites/add/<int:article_pk>", view=views.add_to_favorites_view, name="add_to_favorites"),
    path("favorites/remove/<int:article_pk>", view=views.remove_from_favorites_view, name="remove_from_favorites"),
]

api/urls.py
from django.urls import path

from . import views

app_name = "api"

urlpatterns = [
    path("articles/", view=views.ArticleAPIView.as_view()),
    path("articles/<int:pk>", view=views.RetrieveArticleAPIView.as_view()),
    path("auth/register/", view=views.RegisterAPIView.as_view()),
    path("auth/confirm/<str:code>", view=views.ConfirmUser.as_view())
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="NEWS API",
      default_version='v1',
      description="NEWS API DESCRIPTION",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="dasifue@gmail.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('', include("news.urls")),
    path('accounts/', include("accounts.urls")),
    path('api/auth/', include('djoser.urls.authtoken')),
    path('api/auth/', include('djoser.urls.jwt')),
    path('api/swagger/', schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path

from . import views

app_name = "news"

urlpatterns = [
    path('', views.index, name='index'), #home page
    path('article/<int:pk>', views.article_details_view, name="details"),
    path('article/create/', views.article_creation_view, name="article_creation"),
    path('article/update/<int:pk>', views.article_update_view, name="article_update"),
    path('article/delete/<int:pk>', views.delete_article_view, name="delete_article"),

    path('comment/create/<int:article_pk>', views.create_comment_view, name="comment_create"),
    path('comment/create/<int:article_pk>/parent/<int:parent_pk>', views.create_comment_view, name="comment_answer"),
    path('comment/update/<int:pk>', views.comment_update_view, name="comment_update"),
    path('comment/delete/<int:pk>', views.delete_comment_view, name="comment_delete"),

    path('search/', views.search_view, name="search")
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

    <title>Stand CSS Blog by TemplateMo</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-stand-blog.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
<!--

TemplateMo 551 Stand Blog

https://templatemo.com/tm-551-stand-blog

-->
  </head>

  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="{% url 'news:index' %}"><h2>Stand Blog<em>.</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'news:article_creation' %}">+ New publication
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="{% url 'news:index' %}">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="about.html">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:favorites' %}">Favorites</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'news:search' %}">Search</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="contact.html">Contact Us</a>
              </li>
              <li class="nav-item">
                {% if request.user.is_authenticated %}
                <a class="nav-link" href="contact.html">{{ request.user.username }}</a>
                {% else %}
                <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">Sign In</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:register' %}">Sing Up</a>
                </li>
                {% endif %}
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    {% block content %}

    {% endblock %}
    
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <ul class="social-icons">
              <li><a href="#">Facebook</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Behance</a></li>
              <li><a href="#">Linkedin</a></li>
              <li><a href="#">Dribbble</a></li>
            </ul>
          </div>
          <div class="col-lg-12">
            <div class="copyright-text">
              <p>Copyright 2020 Stand Blog Co.
                    
                 | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
            </div>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script src="{% static 'assets/js/owl.js' %}"></script>
    <script src="{% static 'assets/js/slick.js' %}"></script>
    <script src="{% static 'assets/js/isotope.js' %}"></script>
    <script src="{% static 'assets/js/accordions.js' %}"></script>

    <script language = "text/Javascript"> 
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>

  </body>
</html>