accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", view=views.register_view, name="register"),
    path("login/", view=views.login_view, name="login"),
    path("logout/", view=views.logout_view, name="logout"),

    path("password/change/", view=views.change_password_view, name="change_password"),

    path("favorites/", view=views.favorites_view, name="favorites"),
    path("favorites/add/<int:article_pk>", view=views.add_to_favorites_view, name="add_to_favorites"),
    path("favorites/remove/<int:article_pk>", view=views.remove_from_favorites_view, name="remove_from_favorites"),
]

api/urls.py
from django.urls import path

from . import views

app_name = "api"

urlpatterns = [
    path("articles/", view=views.ArticleAPIView.as_view()),
    path("articles/<int:pk>", view=views.RetrieveArticleAPIView.as_view()),
    path("auth/register/", view=views.RegisterAPIView.as_view()),
    path("auth/confirm/<str:code>", view=views.ConfirmUser.as_view())
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="NEWS API",
      default_version='v1',
      description="NEWS API DESCRIPTION",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="dasifue@gmail.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('', include("news.urls")),
    path('accounts/', include("accounts.urls")),
    path('api/auth/', include('djoser.urls.authtoken')),
    path('api/auth/', include('djoser.urls.jwt')),
    path('api/swagger/', schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path

from . import views

app_name = "news"

urlpatterns = [
    path('', views.index, name='index'), #home page
    path('article/<int:pk>', views.article_details_view, name="details"),
    path('article/create/', views.article_creation_view, name="article_creation"),
    path('article/update/<int:pk>', views.article_update_view, name="article_update"),
    path('article/delete/<int:pk>', views.delete_article_view, name="delete_article"),

    path('comment/create/<int:article_pk>', views.create_comment_view, name="comment_create"),
    path('comment/create/<int:article_pk>/parent/<int:parent_pk>', views.create_comment_view, name="comment_answer"),
    path('comment/update/<int:pk>', views.comment_update_view, name="comment_update"),
    path('comment/delete/<int:pk>', views.delete_comment_view, name="comment_delete"),

    path('search/', views.search_view, name="search")
]

news/models.py
from django.db import models
from accounts.models import User


class Category(models.Model):
    name = models.CharField(verbose_name="Название", max_length=50)

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(verbose_name="Название", max_length=50)

    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"

    def __str__(self):
        return self.name    


class Article(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="articles", verbose_name="Владелец")
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, related_name="articles", null=True, blank=False, verbose_name="Категория")
    tags = models.ManyToManyField(Tag, related_name="articles", verbose_name="Теги", blank=True)
    name = models.CharField(verbose_name="Заголовок", max_length=100)
    content = models.TextField(verbose_name="Контент")
    image = models.ImageField(verbose_name="Изображение", upload_to="articles/", null=True, blank=True)
    created = models.DateTimeField(verbose_name="Дата публикации", auto_now_add=True)
    updated = models.DateTimeField(verbose_name="Дата обновления", auto_now=True)

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

    
    def __str__(self):
        return self.name
    

class Comment(models.Model):
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, related_name="comments", null=True, verbose_name="Владелец")
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments", verbose_name="Публикация")
    comment = models.TextField(verbose_name="Комментарий")
    created = models.DateField(verbose_name="Дата создания", auto_now_add=True)
    updated = models.DateField(verbose_name="Дата обновления", auto_now=True)
    parent = models.ForeignKey("self", on_delete=models.CASCADE, related_name="answers", null=True, blank=True, verbose_name="Родительский комментарий")

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

news/forms.py
from django import forms

from .models import Article, Comment

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ("name", "content", "image", "category")        

    def save(self, owner, *tags) -> Article: # переопределяем метод
        article = Article.objects.create( # создание публикации
            **self.cleaned_data, # передача валидных данных с формы в публикацию
            owner = owner # определение владельца публикации
        )
        
        if tags: # если были переданы теги
            article.tags.add(*tags) # добавляем теги в публикацию

        return article
        

    def update(self, pk, *tags):
        instance = Article.objects.filter(pk=pk).update(
            **self.cleaned_data
            )
        return instance

news/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from accounts.models import User
from .models import Category, Article, Comment
from .forms import ArticleForm
from .utils import find_tags, is_owner

def index(request):
    categories = Category.objects.all()
    articles = Article.objects.all()
    context = {
        "categories": categories,
        "articles": articles
    }
    return render(request, "index.html", context)


def article_details_view(request, pk):

    article = get_object_or_404(Article, pk=pk)   
    comments = article.comments.filter(parent=None)

    context = {
        "article": article,
        "comments": comments,
    }

    return render(request=request, template_name="details.html", context=context)


@login_required
def article_creation_view(request):
    form = ArticleForm() 
    categories = Category.objects.all() 

    if request.method == "POST": # При получении метода POST
        form = ArticleForm(data=request.POST, files=request.FILES) # передаём в форму данные запроса и файлы, отправленные пользователем
        if form.is_valid():
            tags = find_tags(request.POST.get("tags")) # определяем: какие теги ввел пользователь
            form.save(request.user, *tags) # создание публикации
            return redirect("news:index")

    context = {
        "categories": categories,
        "form": form,
    }
    return render(request=request, template_name="article.html", context=context)


@login_required
def create_comment_view(request, article_pk: int, parent_pk: int|None = None):
    user: User = request.user
    article = get_object_or_404(Article, pk=article_pk)
    comment = request.POST.get("comment")

    parent = None
    if parent_pk is not None:
        parent = get_object_or_404(Comment, pk=parent_pk)

    Comment.objects.create(
        owner=user,
        article=article,
        comment=comment,
        parent=parent
    )

    return redirect(request.META.get("HTTP_REFERER", "/"))


@login_required()
@is_owner(model=Article)
def delete_article_view(request, pk: int):
    Article.objects.get(pk=pk).delete()
    return redirect("news:index")


@login_required()
@is_owner(model=Comment)
def delete_comment_view(request, pk: int):
    Comment.objects.get(pk=pk).delete()
    return redirect(request.META.get("HTTP_REFERER", "/"))


@login_required
@is_owner(model=Article)
def article_update_view(request, pk: int):
    article = get_object_or_404(Article, pk=pk)
    form = ArticleForm(instance=article) 
    categories = Category.objects.all() 

    if request.method == "POST": # При получении метода POST
        form = ArticleForm(data=request.POST, files=request.FILES, instance=article) # передаём в форму данные запроса и файлы, отправленные пользователем
        if form.is_valid():
            tags = find_tags(request.POST.get("tags")) # определяем: какие теги ввел пользователь
            form.update(article.id, *tags) # создание публикации
            return redirect("news:details", pk=article.id)

    context = {
        "article": article,
        "categories": categories,
        "form": form,
    }
    return render(request=request, template_name="article_old.html", context=context)


@login_required
@is_owner(model=Comment)
def comment_update_view(request, pk: int):
    comment: Comment = get_object_or_404(Comment, pk=pk)

    if request.method == "POST":
        text = request.POST.get("comment")
        comment.comment = text
        comment.save()
        return redirect("news:details", pk=comment.article.id)
    
    context = {
        "comment": comment
    }
    
    return render(request=request, template_name="comment_update.html", context=context)


def search_view(request):
    search = request.GET.get("search")    
    if search is not None:
        articles = Article.objects.filter(name__icontains=search)
    else:
        articles = Article.objects.all()

    paginator = Paginator(articles, 1)
    articles = paginator.get_page(request.GET.get("page"))

    context = {
        "articles": articles
    }

    return render(request=request, template_name="search.html", context=context)

news/templates/article_old.html
{% extends 'base.html' %}
{% load static %}

{% block content %} 


<section class="contact-us">
    <div class="container">
      <div class="row">
      
        <div class="col-lg-12">
          <div class="down-contact">
            <div class="row">
              <div class="col-lg-8">
                <div class="sidebar-item contact-form">
                  <div class="sidebar-heading">
                    <h2>Send us a message</h2>
                  </div>
                  <div class="content">
                    <form id="contact" action="{% url 'news:article_update' pk=article.pk %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="col-lg-12">
                            <fieldset>
                              <button type="submit" id="form-submit" class="main-button">Submit</button>
                            </fieldset>
                          </div>
                    </form>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="sidebar-item contact-information">
                  <div class="sidebar-heading">
                    <h2>contact information</h2>
                  </div>
                  <div class="content">
                    <ul>
                      <li>
                        <h5>090-484-8080</h5>
                        <span>PHONE NUMBER</span>
                      </li>
                      <li>
                        <h5>info@company.com</h5>
                        <span>EMAIL ADDRESS</span>
                      </li>
                      <li>
                        <h5>123 Aenean id posuere dui, 
                            <br>Praesent laoreet 10660</h5>
                        <span>STREET ADDRESS</span>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

{% endblock %}


    

news/templates/details.html
{% extends 'base.html' %}
{% load static %}

{% block content %} 
 
 <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
        <section class="page-heading">
          <div class="container">
            <div class="row">
              <div class="col-lg-12">
                <div class="text-content">
                  <h4>Post Details</h4>
                  <h2>Single blog post</h2>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
      
      <!-- Banner Ends Here -->
  
      
  
  
      <section class="blog-posts grid-system">
        <div class="container">
          <div class="row">
            <div class="col-lg-8">
              <div class="all-blog-posts">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="blog-post">
                          <div class="blog-thumb">
                            {% if article.image %}
                            <img src="{{ article.image.url }}" alt="">
                            {% endif %}
                          </div>
                          <div class="down-content">
                            <span>{{ article.category.name }}</span>
                            <a href="{% url 'news:details' pk=article.pk %}"><h4>{{ article.name }}</h4></a>
                            <ul class="post-info">
                              <li><a href="#">{{ article.owner.username }}</a></li>
                              <li><a href="#">{{ article.updated }}</a></li>
                              <li><a href="#">12 Comments</a></li>
                            </ul>
                            <p>{{ article.content }}</p>
                            <div class="post-options">
                              <div class="row">
                                <div class="col-6">
                                  <ul class="post-tags">
                                    {% if request.user not in article.users.all %}
                                    <a href="{% url 'accounts:add_to_favorites' article_pk=article.id %}">
                                      <li><i class="fa fa-heart-o"></i></li>
                                      <li>{{ article.users.count }}</li>
                                    </a>
                                    {% else %}
                                    <a href="{% url 'accounts:remove_from_favorites' article_pk=article.id %}">
                                      <li><i class="fa fa-heart"></i></li>
                                      <li>{{ article.users.count }}</li>
                                    </a>
                                    {% endif %}
                                  </ul>
                                  <ul class="post-tags">
                                    <li><i class="fa fa-tags"></i></li>
                                    {% for tag in article.tags.all %}
                                    <li><a href="#">{{ tag.name }}</a></li>
                                    {% endfor %}
                                  </ul>
                                </div>
                                <div class="col-6">
                                  <ul class="post-share">
                                    <li><i class="fa fa-share-alt"></i></li>
                                    <li><a href="#">Facebook</a>,</li>
                                    <li><a href="#"> Twitter</a></li><br>
                                    {% if article.owner == request.user %}
                                    <a href="{% url 'news:delete_article' pk=article.id %}"><li><i class="fa fa-trash"></i></li></a>
                                    <a href="{% url 'news:article_update' pk=article.id %}"><li><i class="fa fa-pencil"></i></li></a>
                                    {% endif %}
                                  </ul>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                  <div class="col-lg-12">
                    <div class="sidebar-item comments">
                      <div class="sidebar-heading">
                        <h2>{{ article.comments.count }} comments</h2>
                      </div>
                      <div class="content">
                        <ul>
                          {% for comment in comments %}
                          <li>
                            <div class="author-thumb">
                              <img src="{{ comment.owner.avatar.url }}" alt="">
                            </div>
                            <div class="right-content">
                              <h4>{{ comment.owner.email }}<span>{{ comment.updated }}</span></h4>
                              <p>{{ comment.comment }}</p>
                              <button class="reply-btn">Ответить</button>
                              {% if comment.owner == request.user %}
                              <a href="{% url 'news:comment_delete' pk=comment.id %}"><li><i class="fa fa-trash"></i></li></a>
                              <a href="{% url 'news:comment_update' pk=comment.id %}"><li><i class="fa fa-pencil"></i></li></a>
                              {% endif %}
                              <div class="reply-form" style="display: none;">
                                <form id="comment" action="{% url 'news:comment_answer' article_pk=article.id parent_pk=comment.id %}" method="post">
                                  {% csrf_token %}
                                  <div class="row">
                                    <div class="col-lg-12">
                                      <fieldset>
                                        <textarea name="comment" rows="6" id="message" placeholder="Type your comment" required></textarea>
                                      </fieldset>
                                    </div>
                                    <div class="col-lg-12">
                                      <fieldset>
                                        <button type="submit" id="form-submit" class="main-button">Submit</button>
                                      </fieldset>
                                    </div>
                                  </div>
                                </form>
                              </div>
                            </div>
                          </li>

                          {% for ans in comment.answers.all %}
                          <li class="replied">
                            <div class="author-thumb">
                              <img src="{{ ans.owner.avatar.url }}" alt="">
                            </div>
                            <div class="right-content">
                              <h4>{{ ans.owner.email }}<span>{{ ans.updated }}</span></h4>
                              <p>{{ ans.comment }}</p>
                            </div>
                          </li>
                          {% endfor %}

                          {% endfor %}

                        </ul>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-12">
                    <div class="sidebar-item submit-comment">
                      <div class="sidebar-heading">
                        <h2>Your comment</h2>
                      </div>
                      <div class="content">
                        <form id="comment" action="{% url 'news:comment_create' article_pk=article.id %}" method="post">
                          {% csrf_token %}
                          <div class="row">
                            <div class="col-lg-12">
                              <fieldset>
                                <textarea name="comment" rows="6" id="message" placeholder="Type your comment" required></textarea>
                              </fieldset>
                            </div>
                            <div class="col-lg-12">
                              <fieldset>
                                <button type="submit" id="form-submit" class="main-button">Submit</button>
                              </fieldset>
                            </div>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="sidebar">
                <div class="row">
                  <div class="col-lg-12">
                    <div class="sidebar-item search">
                      <form id="search_form" name="gs" method="GET" action="#">
                        <input type="text" name="q" class="searchText" placeholder="type to search..." autocomplete="on">
                      </form>
                    </div>
                  </div>
                  <div class="col-lg-12">
                    <div class="sidebar-item recent-posts">
                      <div class="sidebar-heading">
                        <h2>Recent Posts</h2>
                      </div>
                      <div class="content">
                        <ul>
                          <li><a href="post-details.html">
                            <h5>Vestibulum id turpis porttitor sapien facilisis scelerisque</h5>
                            <span>May 31, 2020</span>
                          </a></li>
                          <li><a href="post-details.html">
                            <h5>Suspendisse et metus nec libero ultrices varius eget in risus</h5>
                            <span>May 28, 2020</span>
                          </a></li>
                          <li><a href="post-details.html">
                            <h5>Swag hella echo park leggings, shaman cornhole ethical coloring</h5>
                            <span>May 14, 2020</span>
                          </a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-12">
                    <div class="sidebar-item categories">
                      <div class="sidebar-heading">
                        <h2>Categories</h2>
                      </div>
                      <div class="content">
                        <ul>
                          <li><a href="#">- Nature Lifestyle</a></li>
                          <li><a href="#">- Awesome Layouts</a></li>
                          <li><a href="#">- Creative Ideas</a></li>
                          <li><a href="#">- Responsive Templates</a></li>
                          <li><a href="#">- HTML5 / CSS3 Templates</a></li>
                          <li><a href="#">- Creative &amp; Unique</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-12">
                    <div class="sidebar-item tags">
                      <div class="sidebar-heading">
                        <h2>Tag Clouds</h2>
                      </div>
                      <div class="content">
                        <ul>
                          <li><a href="#">Lifestyle</a></li>
                          <li><a href="#">Creative</a></li>
                          <li><a href="#">HTML5</a></li>
                          <li><a href="#">Inspiration</a></li>
                          <li><a href="#">Motivation</a></li>
                          <li><a href="#">PSD</a></li>
                          <li><a href="#">Responsive</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var replyButtons = document.querySelectorAll('.reply-btn');
    
    replyButtons.forEach(function(button) {
      button.addEventListener('click', function() {
        var replyForm = this.nextElementSibling;
        replyForm.style.display = (replyForm.style.display === 'none' || replyForm.style.display === '') ? 'block' : 'none';
      });
    });
  });
</script>
      
{% endblock %}

news/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="blog-posts grid-system">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="all-blog-posts">
            <div class="row">

             {% for article in articles %}


              <div class="col-lg-6">
                <div class="blog-post">
                    <div class="blog-thumb">
                      {% if article.image %}
                      <img src="{{ article.image.url }}" alt="">
                      {% endif %}
                    </div>
                    <div class="down-content">
                      <span>{{ article.category.name }}</span>
                      <a href="{% url 'news:details' pk=article.pk %}"><h4>{{ article.name }}</h4></a>
                      <ul class="post-info">
                        <li><a href="#">{{ article.owner.username }}</a></li>
                        <li><a href="#">{{ article.updated }}</a></li>
                        <li><a href="#">12 Comments</a></li>
                      </ul>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-6">
                            <ul class="post-tags">
                              {% if request.user not in article.users.all %}
                              <a href="{% url 'accounts:add_to_favorites' article_pk=article.id %}">
                                <li><i class="fa fa-heart-o"></i></li>
                                <li>{{ article.users.count }}</li>
                              </a>
                              {% else %}
                              <a href="{% url 'accounts:remove_from_favorites' article_pk=article.id %}">
                                <li><i class="fa fa-heart"></i></li>
                                <li>{{ article.users.count }}</li>
                              </a>
                              {% endif %}
                            </ul>
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              {% for tag in article.tags.all %}
                              <li><a href="#">{{ tag.name }}</a></li>
                              {% endfor %}
                            </ul>
                          </div>
                          <div class="col-6">
                            <ul class="post-share">
                              <li><i class="fa fa-share-alt"></i></li>
                              <li><a href="#">Facebook</a>,</li>
                              <li><a href="#"> Twitter</a></li><br>
                              {% if article.owner == request.user %}
                              <a href="{% url 'news:delete_article' pk=article.id %}"><li><i class="fa fa-trash"></i></li></a>
                              <a href="{% url 'news:article_update' pk=article.id %}"><li><i class="fa fa-pencil"></i></li></a>
                              {% endif %}
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>

              {% endfor %}
              <div class="col-lg-12">
                <div class="pagination">
                    <span class="step-links">
                        {% if articles.has_previous %}
                            <a href="?{{ request.GET.urlencode }}&page=1">&laquo; first</a>
                            <a href="?{{ request.GET.urlencode }}&page={{ articles.previous_page_number }}">previous</a>
                        {% endif %}
                
                        <span class="current">
                            Page {{ articles.number }} of {{ articles.paginator.num_pages }}.
                        </span>
                
                        {% if articles.has_next %}
                            <a href="?{{ request.GET.urlencode }}&page={{ articles.next_page_number }}">next</a>
                            <a href="?{{ request.GET.urlencode }}&page={{ articles.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="sidebar">
            <div class="row">
              <div class="col-lg-12">
                <div class="sidebar-item search">
                </div>
              </div>
              <div class="col-lg-12">
                <div class="sidebar-item recent-posts">
                  <div class="sidebar-heading">
                    <h2>Search</h2>
                  </div>
                  <div class="content">
                    <form action="{% url 'news:search' %}" method="get">
                        <input type="text" name="search" id="" placeholder="Search...">
                        <button type="submit">0</button>
                    </form>
                  </div>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="sidebar-item categories">
                  <div class="sidebar-heading">
                    <h2>Categories</h2>
                  </div>
                  <div class="content">
                    <ul>
                      <li><a href="#">- Nature Lifestyle</a></li>
                      <li><a href="#">- Awesome Layouts</a></li>
                      <li><a href="#">- Creative Ideas</a></li>
                      <li><a href="#">- Responsive Templates</a></li>
                      <li><a href="#">- HTML5 / CSS3 Templates</a></li>
                      <li><a href="#">- Creative &amp; Unique</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="sidebar-item tags">
                  <div class="sidebar-heading">
                    <h2>Tag Clouds</h2>
                  </div>
                  <div class="content">
                    <ul>
                      <li><a href="#">Lifestyle</a></li>
                      <li><a href="#">Creative</a></li>
                      <li><a href="#">HTML5</a></li>
                      <li><a href="#">Inspiration</a></li>
                      <li><a href="#">Motivation</a></li>
                      <li><a href="#">PSD</a></li>
                      <li><a href="#">Responsive</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}